### PR TITLE
Add python3 support and improve ctypes wrapper

### LINKED ISSUE #3: Can't install on Mac OS X 10.10
Version info and build log below:

```
$ uname -a
Darwin mbp.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

$ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.macosx-10.10-intel-2.7
creating build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/__init__.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/consumer.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/dtrace_structs.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
running build_ext
cythoning dtrace/dtrace.pyx to dtrace/dtrace.c

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, chew_func=None, chewrec_func=None, out_func=None,
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:239:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, chew_func=None, chewrec_func=None, out_func=None,
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:239:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:240:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:240:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:241:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:241:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:242:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:242:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, script, chew_func=None, chewrec_func=None,
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:354:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, script, chew_func=None, chewrec_func=None,
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:354:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:355:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:355:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:356:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:356:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:357:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:357:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object
building 'dtrace' extension
creating build/temp.macosx-10.10-intel-2.7
creating build/temp.macosx-10.10-intel-2.7/dtrace
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c dtrace/dtrace.c -o build/temp.macosx-10.10-intel-2.7/dtrace/dtrace.o
dtrace/dtrace.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command 'cc' failed with exit status 1
```

### LINKED ISSUE #4: Ctypes on Mac OS X
$ python syscall_count_continuous.py
Segmentation fault: 11

$ python -V
Python 2.7.6

xception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000718

VM Regions Near 0x718:
--> 
    __TEXT                 00000001045b4000-00000001045b5000 [    4K] r-x/rwx SM=COW  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdtrace.dylib                 0x00000001049626d5 dtrace_setopt + 253
1   libffi.dylib                    0x00007fff90f98f44 ffi_call_unix64 + 76
2   libffi.dylib                    0x00007fff90f99781 ffi_call + 853
3   _ctypes.so                      0x00000001048c3762 _ctypes_callproc + 874
4   _ctypes.so                      0x00000001048bdbad 0x1048bb000 + 11181
5   org.python.python               0x00000001045c92ac PyObject_Call + 99
6   org.python.python               0x0000000104645c00 PyEval_EvalFrameEx + 11370
7   org.python.python               0x0000000104642d62 PyEval_EvalCodeEx + 1413
8   org.python.python               0x00000001045e730a 0x1045bf000 + 164618
9   org.python.python               0x00000001045c92ac PyObject_Call + 99
10  org.python.python               0x00000001045d40cf 0x1045bf000 + 86223
11  org.python.python               0x00000001045c92ac PyObject_Call + 99
12  org.python.python               0x00000001046103f4 0x1045bf000 + 332788
13  org.python.python               0x000000010460bcfb 0x1045bf000 + 314619
14  org.python.python               0x00000001045c92ac PyObject_Call + 99
15  org.python.python               0x0000000104645c00 PyEval_EvalFrameEx + 11370
16  org.python.python               0x000000010464960e 0x1045bf000 + 566798
17  org.python.python               0x00000001046463e3 PyEval_EvalFrameEx + 13389
18  org.python.python               0x0000000104642d62 PyEval_EvalCodeEx + 1413
19  org.python.python               0x00000001046427d7 PyEval_EvalCode + 54
20  org.python.python               0x00000001046627bd 0x1045bf000 + 669629
21  org.python.python               0x0000000104662860 PyRun_FileExFlags + 133
22  org.python.python               0x00000001046623fd PyRun_SimpleFileExFlags + 769
23  org.python.python               0x0000000104673b23 Py_Main + 3051
24  libdyld.dylib                   0x00007fff89bd35c9 start + 1

### PR DESCRIPTION
**Pull request by arichardson**
This pull requests allows building for python3 and add function
signatures to the ctypes wrapper.

Fixes #3
Fixes #4

### CODE REVIEW

**Comment by arichardson** [comment]
This is a rather large diff, I can split it up into multiple pull requests if needed. Otherwise I'd recommend looking at each of the individual commits rather than the full diff.

**Comment by tmetsch** [comment]
Thanks for this - this is great! Thanks for putting in the time to refactor this. Will need a bit of time to test this (by any chance did you check this on Solaris & FreeBSD & Mac?), but this certainly warrants a new release imho. 

Thanks again, and as usual - drinks on me once when we meet someday :-)

**Comment by arichardson** [comment]
> Thanks for this - this is great! Thanks for putting in the time to refactor this. Will need a bit of time to test this (by any chance did you check this on Solaris & FreeBSD & Mac?), but this certainly warrants a new release imho.
> 
> Thanks again, and as usual - drinks on me once when we meet someday :-)

I have some follow-up fixes for freebsd+macos that I will post as a PR after some minor cleanups.

I've pushed the full set of changes to https://github.com/Cambridge-AdvancedOS/l41-python-dtrace/tree/python3 in case you'd like to have a look at them before I open the pr.

**Comment by tmetsch** [comment]
Ok, that is great to know - I actually do not have access to a current Mac system. Will test this on Solaris so (y)

**Comment by tmetsch** [comment]
Hey, quick Q - have you seen this error when running the simple example for the ctypes examples:

```
$ pfexec python3 syscall_count_own_walk.py 
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "syscall_count_own_walk.py", line 29, in my_walk
    print('{0:4d} > {1:60s}'.format(instance, name))
TypeError: unsupported format string passed to bytes.__format__
```

**Comment by arichardson** [comment]
I didn't run that example, but I can try running them all with py2+3

**Comment by tmetsch** [comment]
Seems to be an issue with how the data is provided to the callback. Looks like it is a byte array now, proper formatting fixes it.

**Comment by tmetsch** [comment]
This is a "preview" branch of this PR - did some minor code style changes here and there. This seems to work on Solaris (OmniOS) atm with python 3. Need to check python 2 - once it is backward compatible will merge with the master branch or decide to make python 3 a requirement (it is EoY 2020 after all).

https://github.com/tmetsch/python-dtrace/tree/arichardson-python3-support

**Comment by arichardson** [comment]
@tmetsch Thanks! I checked the hello world example with python2, but I can also make sure the other works for one last py2 release if you'd like?

**Comment by tmetsch** [comment]
This looks all good - I did merge it into the master now. All examples did run with python 2 & 3 on OmniOS. So did the unittests etc. Thanks so much for this - this is awesome!!

**Pull request merged**
